name: Blitz Quiz App CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: [macos-latest, Ubuntu-latest, windows-lastest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.JS version 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm run build
