name: Blitz Quiz App CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    env:
      CI: true
    strategy:
      matrix:
        node-version: [16.x]
        platform: [macos-latest, Ubuntu-latest]
    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.JS version ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - run: npm install
      - run: npm run build
      - run: npm run db-deploy
      - run: npm run test
